export let verbs = [
    "kills",
    "murders",
    "causes",
    "touches",
    "falls",
    "accepts",
    "accomplishes",
    "achieves",
    "acts",
    "activates",
    "adapts",
    "adds",
    "addresses",
    "admits",
    "adopts",
    "affords",
    "alerts",
    "annoys",
    "amuses",
    "applauds",
    "builds",
    "calls",
    "charges",
    "chases",
    "chooses",
    "freezes",
    "frightens",
    "fries",
    "gets",
    "gives",
    "grabs",
    "grips",
    "hammers",
    "harasses",
    "harms",
    "haunts",
    "interrogates",
    "discovers",
    "jails",
    "kisses",
    "hugs",
    "shakes",
    "learns",
    "lectures",
    "overtakes",
    "promotes",
    "perserves",
    "promises",
    "purchases",
    "questions",
    "sails",
    "runs",
    "seals",
    "searches",
    "selects",
    "sells",
    "rents",
    "settles",
    "scolds",
    "destroys",
    "obliterates",
    "damages",
    "rocks",
    "risks",
    "bets",
    "gambles",
    "saves"
]

export let transitions = [
    "which causes",
    "thus",
    "therefore",
    "but",
    "although",
    "and",
    "leading to",
    "causing",
    "triggering",
    "which butterfly effects to",
    "meanwhile",
    "simultaneously",
    "because",
    "due to",
    "since",
    "as",
    "so",
    "as a result",
    "therefore",
    "subsequently",
    "consequently",
    "hence",
    "even so",
    "however",
    "in contrast",
    "nevertheless",
    "notwithstanding",
    "on the contrary",
    "otherwise",
    "and yet",
    "still",
    "for this purpose",
    "to this end",
    "with this object",
    "nearby",
    "later",
    "after",
    "immediately",
    "in the meantime",
    "now",
    "then",
    "while"
]

export function getStartingPrompt() {
    let i = Math.floor(Math.random() * startingPrompt.length);
    console.log(startingPrompt[i]);
    return startingPrompt[i];
}

let startingPrompt = [
    "person",
    "character",
    "yellow",
    "blue",
    "hero",
    "boy",
    "man",
    "girl",
    "protagonist",
    "red",
    "green",
    "white",
    "black",
    "brown",
    "purple"
]